solve issues #17...19
linux-system-roles/sap-netweaver-preconfigure pull request #20
Opened 2021-01-25 15:20 UTC by berndfinger

2021-01-26 14:55 UTC, richm approved these changes
lgtm

2021-01-26 14:59 UTC, richm approved these changes
lgtm

2021-01-27 16:05 UTC, richm commented on tasks/sapnote/assert-2526952.yml
> +- name: Report tuned-profiles-sap-hana version
sap or sap-hana?

2021-01-27 16:59 UTC, rhmk requested changes
lgtm

2021-01-27 17:16 UTC, berndfinger commented on tasks/sapnote/assert-2526952.yml
> +- name: Report tuned-profiles-sap-hana version
thanks

2021-01-27 17:20 UTC, richm approved these changes
lgtm

2021-01-27 17:41 UTC, merged